@echo off
setlocal EnableDelayedExpansion

::: Star Citizen Telemetry Hub - Python setup check
::: Pattern follows libthirdspacevest-simhub (windows/setup/check-python.bat).
:::
::: Usage: call setup\check-python.bat
::: On success exports STH_PYTHON to the caller.

echo [CHECK] Checking Python installation...

if exist "%~dp0..\.env.bat" call "%~dp0..\.env.bat"

set "DETECTED_PYTHON="
set "DETECTED_VERSION="
set "DETECTION_METHOD="

if defined STH_PYTHON (
  set "DETECTED_PYTHON=!STH_PYTHON!"
  set "DETECTION_METHOD=STH_PYTHON from windows\.env.bat"
  goto :verify_python
)

where py >nul 2>&1
if !ERRORLEVEL! equ 0 (
  for %%P in (14 13 12 11 10) do (
    py -3.%%P -c "import sys" >nul 2>&1
    if !ERRORLEVEL! equ 0 (
      set "DETECTED_PYTHON=py -3.%%P"
      set "DETECTION_METHOD=py launcher (Python 3.%%P)"
      goto :verify_python
    )
  )
)

where python >nul 2>&1
if !ERRORLEVEL! equ 0 (
  set "DETECTED_PYTHON=python"
  set "DETECTION_METHOD=python on PATH"
  goto :verify_python
)

where python3 >nul 2>&1
if !ERRORLEVEL! equ 0 (
  set "DETECTED_PYTHON=python3"
  set "DETECTION_METHOD=python3 on PATH"
  goto :verify_python
)

echo [FAIL] Python is not installed or not on PATH.
echo Install Python 3.10+ from https://www.python.org/downloads/ ^(check "Add to PATH"^).
exit /b 1

:verify_python
for /f "tokens=*" %%i in ('%DETECTED_PYTHON% --version 2^>^&1') do set "DETECTED_VERSION=%%i"

%DETECTED_PYTHON% -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" >nul 2>&1
if !ERRORLEVEL! neq 0 (
  echo [FAIL] %DETECTED_VERSION% is too old or not working.
  echo Please install Python 3.10 or newer.
  exit /b 1
)

echo [OK] %DETECTED_VERSION%
echo Detected via: %DETECTION_METHOD%
echo Command: %DETECTED_PYTHON%

if not exist "%~dp0..\.env.bat" (
  echo.
  echo Save this interpreter to windows\.env.bat so all scripts use the same Python?
  set /p "SAVE_ENV= Save to .env.bat? [Y/n]: "
  if /i "!SAVE_ENV!"=="" set "SAVE_ENV=Y"
  if /i "!SAVE_ENV!"=="Y" (
    echo @echo off> "%~dp0..\.env.bat"
    echo REM Star Citizen Telemetry Hub - local Python override>> "%~dp0..\.env.bat"
    echo REM Generated by check-setup.bat - edit STH_PYTHON as needed.>> "%~dp0..\.env.bat"
    echo.>> "%~dp0..\.env.bat"
    echo set "STH_PYTHON=!DETECTED_PYTHON!">> "%~dp0..\.env.bat"
    echo.
    echo [OK] Created windows\.env.bat with STH_PYTHON=!DETECTED_PYTHON!
  )
) else (
  if not defined STH_PYTHON (
    echo.
    echo [INFO] windows\.env.bat exists but STH_PYTHON is not set.
    echo Add a line such as: set "STH_PYTHON=!DETECTED_PYTHON!"
  )
)

set "EXPORT_PYTHON=!DETECTED_PYTHON!"
endlocal & set "STH_PYTHON=%EXPORT_PYTHON%" & set "PYTHON_CMD=%EXPORT_PYTHON%"
exit /b 0
